name: "Client Setup"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"
        cache-dependency-path: pnpm-lock.yaml
    - name: Restore node_modules Cache
      id: pnpm-cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
    - name: Install Dependencies
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      run: pnpm install
      shell: bash
