name: "Continuous Integration"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: node_modules
          key: js-depend-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: pnpm install
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: js-depend-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: npm run lint

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: js-depend-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: npm run coverage
      - uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: js-depend-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: npm run build

  build-storybook:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: js-depend-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: npm run build-storybook

  finish:
    needs: [lint, test, build, build-storybook]
    runs-on: ubuntu-latest
    steps:
      - run: echo "finish"
