name: "Continuous Integration"
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composite_actions/client-setup

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composite_actions/client-setup
      - run: npm run lint

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composite_actions/client-setup
      - run: npx vitest --coverage.enabled true
      - name: report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composite_actions/client-setup
      - run: npm run build

  build-storybook:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composite_actions/client-setup
      - run: npm run build-storybook

  complete-ci:
    needs: [lint, test, build, build-storybook]
    runs-on: ubuntu-latest
    steps:
      - run: echo "complete"
